#import "DYYYSettingSectionProvider.h"
#import "DYYYSettingViewController.h"
#import "DYYYSettingItem.h"

@implementation DYYYSettingSectionProvider

+ (NSArray<NSArray<DYYYSettingItem *> *> *)defaultSections {
    return @[
            // ===== 一、播放 =====
            @[
                [DYYYSettingItem itemWithGroupTitle:@"弹幕与进度"],
                [DYYYSettingItem itemWithTitle:@"启用弹幕改色" key:@"DYYYEnableDanmuColor" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"自定弹幕颜色" key:@"DYYYdanmuColor" type:DYYYSettingItemTypeTextField placeholder:@"十六进制"],
                [DYYYSettingItem itemWithTitle:@"显示进度时长" key:@"DYYYisShowScheduleDisplay" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"进度纵轴位置" key:@"DYYYTimelineVerticalPosition" type:DYYYSettingItemTypeTextField placeholder:@"-12.5"],
                [DYYYSettingItem itemWithTitle:@"时间进度位置" key:@"DYYYScheduleStyle" type:DYYYSettingItemTypeCustomPicker placeholder:@"点击选择"],
                [DYYYSettingItem itemWithTitle:@"进度标签颜色" key:@"DYYYProgressLabelColor" type:DYYYSettingItemTypeTextField placeholder:@"十六进制"],
                [DYYYSettingItem itemWithTitle:@"隐藏视频进度" key:@"DYYYHideVideoProgress" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏章节进度条" key:@"DYYYHideChapterProgress" type:DYYYSettingItemTypeSwitch],

                [DYYYSettingItem itemWithGroupTitle:@"播放行为"],
                [DYYYSettingItem itemWithTitle:@"强制自动播放（不能关闭）" key:@"DYYYisEnableAutoPlay" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"禁用点击首页刷新" key:@"DYYYDisableHomeRefresh" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"禁用双击视频点赞" key:@"DYYYDouble" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"关注二次确认" key:@"DYYYfollowTips" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"收藏二次确认" key:@"DYYYcollectTips" type:DYYYSettingItemTypeSwitch],

                [DYYYSettingItem itemWithGroupTitle:@"倍速"],
                [DYYYSettingItem itemWithTitle:@"默认倍速（如果没有倍数设置）" key:@"DYYYDefaultSpeed" type:DYYYSettingItemTypeSpeedPicker placeholder:@"点击选择"],
                [DYYYSettingItem itemWithTitle:@"长按倍速" key:@"DYYYLongPressSpeed" type:DYYYSettingItemTypeSpeedPicker placeholder:@"点击选择"],
                [DYYYSettingItem itemWithTitle:@"上下手势控制倍速" key:@"DYYYEnableLongPressSpeedGesture" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"倍速按钮功能-开关" key:@"DYYYEnableFloatSpeedButton" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"倍速数值（强制倍数）" key:@"DYYYSpeedSettings" type:DYYYSettingItemTypeTextField placeholder:@"英文逗号分隔"],
                [DYYYSettingItem itemWithTitle:@"下一个视频会自动恢复默认倍速" key:@"DYYYAutoRestoreSpeed" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"倍速按钮显示后缀" key:@"DYYYSpeedButtonShowX" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"倍速按钮大小" key:@"DYYYSpeedButtonSize" type:DYYYSettingItemTypeTextField placeholder:@"默认40"],

                [DYYYSettingItem itemWithGroupTitle:@"清屏"],
                [DYYYSettingItem itemWithTitle:@"视频清屏隐藏-开关" key:@"DYYYEnableFloatClearButton" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -按钮大" key:@"DYYYCustomAlbumSizeLarge" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -按钮中" key:@"DYYYCustomAlbumSizeMedium" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -按钮小" key:@"DYYYCustomAlbumSizeSmall" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -按钮自定义" key:@"DYYYEnableFloatClearButtonSize" type:DYYYSettingItemTypeTextField placeholder:@"默认40"],
                [DYYYSettingItem itemWithTitle:@"清屏按钮图标-开关" key:@"DYYYEnableCustomAlbum" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -清屏本地相册" key:@"DYYYCustomAlbumImage" type:DYYYSettingItemTypeTextField placeholder:@"点击选择图片"],
                [DYYYSettingItem itemWithTitle:@"  -清屏隐藏弹幕" key:@"DYYYHideDanmaku" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -清屏移除进度" key:@"DYYYEnabshijianjindu" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -清屏隐藏进度" key:@"DYYYHideTimeProgress" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -清屏隐藏章节" key:@"DYYYHideChapter" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -清屏隐藏滑条" key:@"DYYYHideSlider" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -清屏隐藏底栏" key:@"DYYYHideTabBar" type:DYYYSettingItemTypeSwitch],

                [DYYYSettingItem itemWithGroupTitle:@"画质与清晰度"],
                [DYYYSettingItem itemWithTitle:@"弹出-清晰度选项" key:@"DYYYShowAllVideoQuality" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"默认最高画质" key:@"DYYYEnableVideoHighestQuality" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"默认清晰度-最高" key:@"DYYYDefaultQualityBest" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"默认清晰度-原画" key:@"DYYYDefaultQualityOriginal" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"默认清晰度-1080P" key:@"DYYYDefaultQuality1080p" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"默认清晰度-720P" key:@"DYYYDefaultQuality720p" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"视频降噪增强" key:@"DYYYEnableNoiseFilter" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"屏蔽HDR视频" key:@"DYYYFilterFeedHDR" type:DYYYSettingItemTypeSwitch],

                [DYYYSettingItem itemWithGroupTitle:@"播放页元素"],
                [DYYYSettingItem itemWithTitle:@"隐藏点赞数值" key:@"DYYYHideLikeLabel" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏评论数值" key:@"DYYYHideCommentLabel" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏收藏数值" key:@"DYYYHideCollectLabel" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏分享数值" key:@"DYYYHideShareLabel" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏点赞按钮" key:@"DYYYHideLikeButton" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏评论按钮" key:@"DYYYHideCommentButton" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏收藏按钮" key:@"DYYYHideCollectButton" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏头像按钮" key:@"DYYYHideAvatarButton" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏音乐按钮" key:@"DYYYHideMusicButton" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏分享按钮" key:@"DYYYHideShareButton" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏全屏观看" key:@"DYYYisHiddenEntry" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"启用保存他人头像" key:@"DYYYEnableSaveAvatar" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏头像列表" key:@"DYYYisHiddenAvatarList" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏头像加号" key:@"DYYYHideLOTAnimationView" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏弹幕按钮" key:@"DYYYHideDanmuButton" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏取消静音" key:@"DYYYHideCancelMute" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏去汽水听" key:@"DYYYHideQuqishuiting" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏视频定位" key:@"DYYYHideLocation" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏相关搜索" key:@"DYYYHideInteractionSearch" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏进入直播" key:@"DYYYHideEnterLive" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏共创头像" key:@"DYYYHideGongChuang" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏底部相关" key:@"DYYYHideBottomRelated" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏拍摄同款" key:@"DYYYHideFeedAnchorContainer" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏挑战贴纸" key:@"DYYYHideChallengeStickers" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏分享私信" key:@"DYYYHidePrivateMessages" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"时间标签颜色" key:@"DYYYLabelColor" type:DYYYSettingItemTypeTextField placeholder:@"十六进制"]
            ],

            // ===== 二、手势与快捷 =====
            @[
                [DYYYSettingItem itemWithGroupTitle:@"长按功能"],
                [DYYYSettingItem itemWithTitle:@"长按功能-开关" key:@"DYYYLongPressDownload" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -保存视频" key:@"DYYYLongPressSaveVideo" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -分享音频" key:@"DYYYLongPressSaveAudio" type:DYYYSettingItemTypeSwitch],
#ifndef DYYY_RELEASE_BUILD
                [DYYYSettingItem itemWithTitle:@"  -启用FLEX" key:@"DYYYEnableFLEX" type:DYYYSettingItemTypeSwitch],
#endif
                [DYYYSettingItem itemWithTitle:@"  -PIP小窗播放" key:@"DYYYLongPressPip" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -保存当前图片" key:@"DYYYLongPressSaveCurrentImage" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -保存所有图片" key:@"DYYYLongPressSaveAllImages" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -复制链接" key:@"DYYYLongPressCopyLink" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -接口解析" key:@"DYYYLongPressApiDownload" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -过滤用户" key:@"DYYYLongPressFilterUser" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -过滤文案" key:@"DYYYLongPressFilterTitle" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -定时关闭" key:@"DYYYLongPressTimerClose" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -制作视频" key:@"DYYYLongPressCreateVideo" type:DYYYSettingItemTypeSwitch],

                [DYYYSettingItem itemWithGroupTitle:@"长按面板复制"],
                [DYYYSettingItem itemWithTitle:@"长按面板-复制功能" key:@"DYYYCopyText" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -复制原文本" key:@"DYYYCopyOriginalText" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -复制分享链接" key:@"DYYYCopyShareLink" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"长按-复制视频文案" key:@"DYYYLongPressCopyTextEnabled" type:DYYYSettingItemTypeSwitch],

                [DYYYSettingItem itemWithGroupTitle:@"长按面板按钮"],
                [DYYYSettingItem itemWithTitle:@"隐藏长按-转发日常" key:@"DYYYHideDaily" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏长按-推荐" key:@"DYYYHideRecommend" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏长按-不感兴趣" key:@"DYYYHideNotInterested" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏长按-举报" key:@"DYYYHideReport" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏长按-倍速（清屏+长按面板）" key:@"DYYYHideSpeed" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏长按-清屏播放" key:@"DYYYHideClearScreen" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏长按-缓存视频" key:@"DYYYHideFavorite" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏长按-稍后再看" key:@"DYYYHideLater" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏长按-投屏" key:@"DYYYHideCast" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏长按-PC打开" key:@"DYYYHideOpenInPC" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏长按-弹幕" key:@"DYYYHideSubtitle" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏长按-自动连播" key:@"DYYYHideAutoPlay" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏长按-识别图片" key:@"DYYYHideSearchImage" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏长按-听抖音" key:@"DYYYHideListenDouyin" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏长按-后台播放" key:@"DYYYHideBackgroundPlay" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏长按-双列入口" key:@"DYYYHideBiserial" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏长按-定时关闭" key:@"DYYYHideTimerclose" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏长按-保存至相册" key:@"DYYYHideSaveToAlbum" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏长按-识图搜同款" key:@"DYYYHideImageSearch" type:DYYYSettingItemTypeSwitch],

                [DYYYSettingItem itemWithGroupTitle:@"双击操作"],
                [DYYYSettingItem itemWithTitle:@"双击操作-开关" key:@"DYYYEnableDoubleOpenAlertController" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -保存视频/图片/实况动图" key:@"DYYYDoubleTapDownload" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -音频弹出分享" key:@"DYYYDoubleTapDownloadAudio" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -复制文案" key:@"DYYYDoubleTapCopyDesc" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -打开评论" key:@"DYYYDoubleTapComment" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -点赞视频" key:@"DYYYDoubleTapLike" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -分享视频" key:@"DYYYDoubleTapshowSharePanel" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -长按面板" key:@"DYYYDoubleTapshowDislikeOnVideo" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -接口解析" key:@"DYYYDoubleInterfaceDownload" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -PIP小窗播放" key:@"DYYYEnablePipPlayer" type:DYYYSettingItemTypeSwitch]
            ],

            // ===== 三、页面设置 =====
            @[
                [DYYYSettingItem itemWithGroupTitle:@"界面设置"],
                [DYYYSettingItem itemWithTitle:@"设置顶栏文字透明" key:@"DYYYtopbartransparent" type:DYYYSettingItemTypeTextField placeholder:@"0-1小数"],
                [DYYYSettingItem itemWithTitle:@"设置全局透明" key:@"DYYYGlobalTransparency" type:DYYYSettingItemTypeTextField placeholder:@"0-1小数"],
                [DYYYSettingItem itemWithTitle:@"首页头像透明" key:@"DYYYAvatarViewTransparency" type:DYYYSettingItemTypeTextField placeholder:@"0-1小数"],
                [DYYYSettingItem itemWithTitle:@"右侧栏缩放度" key:@"DYYYElementScale" type:DYYYSettingItemTypeTextField placeholder:@"不填默认"],
                [DYYYSettingItem itemWithTitle:@"昵称文案缩放" key:@"DYYYNicknameScale" type:DYYYSettingItemTypeTextField placeholder:@"不填默认"],
                [DYYYSettingItem itemWithTitle:@"昵称下移距离" key:@"DYYYNicknameVerticalOffset" type:DYYYSettingItemTypeTextField placeholder:@"不填默认"],
                [DYYYSettingItem itemWithTitle:@"文案下移距离" key:@"DYYYDescriptionVerticalOffset" type:DYYYSettingItemTypeTextField placeholder:@"不填默认"],
                [DYYYSettingItem itemWithTitle:@"属地下移距离" key:@"DYYYIPLabelVerticalOffset" type:DYYYSettingItemTypeTextField placeholder:@"不填默认"],
                [DYYYSettingItem itemWithTitle:@"设置首页标题" key:@"DYYYIndexTitle" type:DYYYSettingItemTypeTextField placeholder:@"不填默认"],
                [DYYYSettingItem itemWithTitle:@"设置朋友标题" key:@"DYYYFriendsTitle" type:DYYYSettingItemTypeTextField placeholder:@"不填默认"],
                [DYYYSettingItem itemWithTitle:@"设置消息标题" key:@"DYYYMsgTitle" type:DYYYSettingItemTypeTextField placeholder:@"不填默认"],
                [DYYYSettingItem itemWithTitle:@"设置我的标题" key:@"DYYYSelfTitle" type:DYYYSettingItemTypeTextField placeholder:@"不填默认"],
                [DYYYSettingItem itemWithTitle:@"设置顶栏横幅" key:@"DYYYModifyTopTabText" type:DYYYSettingItemTypeTextField placeholder:@"格式:原标题=新标题"],
                [DYYYSettingItem itemWithTitle:@"首页全屏+透明" key:@"DYYYisEnableFullScreen" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏系统顶栏" key:@"DYYYisHideStatusbar" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"作品详情页底栏移除" key:@"DYYYDetailHideBottomBar" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"菜单背景颜色" key:@"DYYYBackgroundColor" type:DYYYSettingItemTypeColorPicker],
                [DYYYSettingItem itemWithTitle:@"启用深色键盘" key:@"DYYYisDarkKeyBoard" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"头像文本-修改" key:@"DYYYAvatarTapText" type:DYYYSettingItemTypeTextField placeholder:@"可以自定义修改"],

                [DYYYSettingItem itemWithGroupTitle:@"底栏"],
                [DYYYSettingItem itemWithTitle:@"隐藏底栏商城" key:@"DYYYHideShopButton" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏底栏消息" key:@"DYYYHideMessageButton" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏底栏朋友" key:@"DYYYHideFriendsButton" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏底栏加号" key:@"DYYYisHiddenJia" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏底栏红点" key:@"DYYYisHiddenBottomDot" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏底栏背景" key:@"DYYYisHiddenBottomBg" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏我的按钮" key:@"DYYYHideMyButton" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏发作品框" key:@"DYYYHidePostView" type:DYYYSettingItemTypeSwitch],

                [DYYYSettingItem itemWithGroupTitle:@"侧栏与入口"],
                [DYYYSettingItem itemWithTitle:@"隐藏侧栏红点" key:@"DYYYisHiddenSidebarDot" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏左侧边栏" key:@"DYYYisHiddenLeftSideBar" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"简化侧边栏" key:@"DYYYStreamlinethesidebar" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏双栏入口" key:@"DYYYHideDoubleColumnEntry" type:DYYYSettingItemTypeSwitch],

                [DYYYSettingItem itemWithGroupTitle:@"顶栏与搜索"],
                [DYYYSettingItem itemWithTitle:@"隐藏顶栏红点" key:@"DYYYHideTopBarBadge" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏顶栏横线" key:@"DYYYHidentopbarprompt" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏顶栏引导提示" key:@"DYYYHideFeedTabJumpGuide" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏右上搜索" key:@"DYYYHideDiscover" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏返回按钮" key:@"DYYYHideBack" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏搜索指示条" key:@"DYYYHideSearchEntranceIndicator" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏视频搜索长框" key:@"DYYYHideSearchEntrance" type:DYYYSettingItemTypeSwitch],

                [DYYYSettingItem itemWithGroupTitle:@"频道移除"],
                [DYYYSettingItem itemWithTitle:@"移除推荐" key:@"DYYYHideHotContainer" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"移除关注" key:@"DYYYHideFollow" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"移除精选" key:@"DYYYHideMediumVideo" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"移除商城" key:@"DYYYHideMall" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"移除朋友" key:@"DYYYHideFriend" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"移除同城" key:@"DYYYHideNearby" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"移除团购" key:@"DYYYHideGroupon" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"移除直播" key:@"DYYYHideTabLive" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"移除热点" key:@"DYYYHidePadHot" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"移除经验" key:@"DYYYHideHangout" type:DYYYSettingItemTypeSwitch],

                [DYYYSettingItem itemWithGroupTitle:@"图标"],
                [DYYYSettingItem itemWithTitle:@"未点赞图标" key:@"DYYYIconLikeBefore" type:DYYYSettingItemTypeTextField placeholder:@"点击选择图片"],
                [DYYYSettingItem itemWithTitle:@"已点赞图标" key:@"DYYYIconLikeAfter" type:DYYYSettingItemTypeTextField placeholder:@"点击选择图片"],
                [DYYYSettingItem itemWithTitle:@"评论的图标" key:@"DYYYIconComment" type:DYYYSettingItemTypeTextField placeholder:@"点击选择图片"],
                [DYYYSettingItem itemWithTitle:@"未收藏图标" key:@"DYYYIconUnfavorite" type:DYYYSettingItemTypeTextField placeholder:@"点击选择图片"],
                [DYYYSettingItem itemWithTitle:@"已收藏图标" key:@"DYYYIconFavorite" type:DYYYSettingItemTypeTextField placeholder:@"点击选择图片"],
                [DYYYSettingItem itemWithTitle:@"分享的图标" key:@"DYYYIconShare" type:DYYYSettingItemTypeTextField placeholder:@"点击选择图片"],

                [DYYYSettingItem itemWithGroupTitle:@"液态玻璃"],
                [DYYYSettingItem itemWithTitle:@"评论区毛玻璃" key:@"DYYYisEnableCommentBlur" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"毛玻璃透明度" key:@"DYYYCommentBlurTransparent" type:DYYYSettingItemTypeTextField placeholder:@"0-1小数"],
                [DYYYSettingItem itemWithTitle:@"评论区液态玻璃" key:@"DYYYCommentGlass" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"评论区清透玻璃" key:@"DYYYCommentGlassClear" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"移除评论区底栏" key:@"DYYYHideCommentBottomBar" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"评论区图片清理底栏" key:@"DYYYCommentMediaCleanBottomBar" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"通知玻璃效果" key:@"DYYYEnableNotificationTransparency" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"通知圆角半径" key:@"DYYYNotificationCornerRadius" type:DYYYSettingItemTypeTextField placeholder:@"默认12"],
                [DYYYSettingItem itemWithTitle:@"应用内通知液态玻璃" key:@"DYYYInnerNotiGlass" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"通知清透玻璃" key:@"DYYYInnerNotiGlassClear" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"通知圆角" key:@"DYYYInnerNotiCorner" type:DYYYSettingItemTypeSlider defaultInteger:100],
                [DYYYSettingItem itemWithTitle:@"启用新版玻璃面板" key:@"DYYYisEnableModern" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"悬浮玻璃底栏" key:@"DYYYGlassTabBar" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"底栏清透玻璃" key:@"DYYYGlassTabBarClear" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"分享面板液态玻璃" key:@"DYYYSharePanelGlass" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"分享清透玻璃" key:@"DYYYSharePanelGlassClear" type:DYYYSettingItemTypeSwitch],

                [DYYYSettingItem itemWithGroupTitle:@"音频可视化"],
                [DYYYSettingItem itemWithTitle:@"音频可视化位置" key:@"DYYYAudioVizPosition" type:DYYYSettingItemTypeChoice options:@[@"关闭", @"胶囊上方水平", @"胶囊整栏环绕", @"拍摄圆键环绕"]],
                [DYYYSettingItem itemWithTitle:@"音频可视化形态" key:@"DYYYAudioVizStyle" type:DYYYSettingItemTypeChoice options:@[@"离散条", @"连续流体"]]
            ],

            // ===== 四、内容与过滤 =====
            @[
                [DYYYSettingItem itemWithGroupTitle:@"内容过滤"],
                [DYYYSettingItem itemWithTitle:@"过滤直播" key:@"DYYYisSkipLive" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"过滤热点" key:@"DYYYisSkipHotSpot" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"过滤图集" key:@"DYYYSkipPhoto" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"过滤图文" key:@"DYYYSkipPhotoText" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"过滤音乐卡" key:@"DYYYSkipMusic" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"过滤抖音AI" key:@"DYYYSkipAIInteraction" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"过滤道具" key:@"DYYYFilterProp" type:DYYYSettingItemTypeTextField placeholder:@"英文逗号分隔"],
                [DYYYSettingItem itemWithTitle:@"过滤低赞" key:@"DYYYfilterLowLikes" type:DYYYSettingItemTypeTextField placeholder:@"填0关闭"],
                [DYYYSettingItem itemWithTitle:@"过滤文案" key:@"DYYYfilterKeywords" type:DYYYSettingItemTypeTextField placeholder:@"不填关闭"],
                [DYYYSettingItem itemWithTitle:@"视频时限" key:@"DYYYfiltertimelimit" type:DYYYSettingItemTypeTextField placeholder:@"填0关闭，单位为天"],
                [DYYYSettingItem itemWithTitle:@"禁用自动进入直播" key:@"DYYYDisableAutoEnterLive" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"拦截广告（开屏、信息流、启动视频）" key:@"DYYYNoAds" type:DYYYSettingItemTypeSwitch],

                [DYYYSettingItem itemWithGroupTitle:@"作品附加与提示"],
                [DYYYSettingItem itemWithTitle:@"隐藏视频合集" key:@"DYYYHideTemplateVideo" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏短剧合集" key:@"DYYYHideTemplatePlaylet" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏动图标签" key:@"DYYYHideLiveGIF" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏笔记标签" key:@"DYYYHideItemTag" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏底部话题" key:@"DYYYHideTemplateGroup" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏相机定位" key:@"DYYYHideCameraLocation" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏视频滑条" key:@"DYYYHideStoryProgressSlide" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏图片滑条" key:@"DYYYHideDotsIndicator" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏昵称右侧" key:@"DYYYHideRightLable" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏暂停关键词" key:@"DYYYHidePauseVideoRelatedWord" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏作者声明" key:@"DYYYHideAntiAddictedNotice" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏推荐提示" key:@"DYYYHideRecommendTips" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏分享提示" key:@"DYYYHideShareContentView" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏热点提示" key:@"DYYYHideHotspot" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏吃喝玩乐" key:@"DYYYHideNearbyCapsuleView" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏校园提示" key:@"DYYYHideTemplateTags" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏作者店铺" key:@"DYYYHideHisShop" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏关注直播" key:@"DYYYHideConcernCapsuleView" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏关注顶端" key:@"DYYYHidenLiveView" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏同城顶端" key:@"DYYYHideMenuView" type:DYYYSettingItemTypeSwitch]
            ],

            // ===== 五、互动 =====
            @[
                [DYYYSettingItem itemWithGroupTitle:@"评论区"],
                [DYYYSettingItem itemWithTitle:@"隐藏评论视图" key:@"DYYYHideCommentViews" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏评论背景" key:@"DYYYHideComment" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏回复框" key:@"DYYYHideReply" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏评论搜索" key:@"DYYYHideCommentDiscover" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏评论提示" key:@"DYYYHideCommentTips" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏评论音乐" key:@"DYYYHideCommentMusicAnchor" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏评论定位" key:@"DYYYHidePOIEntryAnchor" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"聊天评论透明" key:@"DYYYHideChatCommentBg" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏短剧免费去看" key:@"DYYYHideShowPlayletComment" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏搜索引导提示框" key:@"DYYYHideGuideTipView" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏关注提示视图" key:@"DYYYHideFollowPromptView" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"评论区-双击触发" key:@"DYYYEnableDoubleOpenComment" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"评论文本复制" key:@"DYYYCommentCopyText" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"评论区-长按复制文本" key:@"DYYYEnableCommentCopyText" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"评论区-保存动态图" key:@"DYYYCommentLivePhotoNotWaterMark" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"评论区-保存图片" key:@"DYYYCommentNotWaterMark" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"评论区-保存表情包" key:@"DYYYFourceDownloadEmotion" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"表情预览保存" key:@"DYYYForceDownloadPreviewEmotion" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"启用音乐文本复制" key:@"DYYYMusicCopyText" type:DYYYSettingItemTypeSwitch],

                [DYYYSettingItem itemWithGroupTitle:@"直播"],
                [DYYYSettingItem itemWithTitle:@"隐藏直播胶囊" key:@"DYYYHideLiveCapsuleView" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏群直播中" key:@"DYYYGroupLiving" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏直播广场" key:@"DYYYHideLivePlayground" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏礼物展馆" key:@"DYYYHideGiftPavilion" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏退出清屏" key:@"DYYYHideLiveRoomClear" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏投屏按钮" key:@"DYYYHideLiveRoomMirroring" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏直播发现" key:@"DYYYHideLiveDiscovery" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏直播点歌" key:@"DYYYHideKTVSongIndicator" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏流量提醒" key:@"DYYYHideCellularAlert" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏直播间设置" key:@"DYYYHideLiveRoomClose" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏直播间横屏" key:@"DYYYHideLiveRoomFullscreen" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏直播商品信息" key:@"DYYYHideLiveGoodsMsg" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏直播点赞动画" key:@"DYYYHideLiveLikeAnimation" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏激励红包挂件" key:@"DYYYHidePendantGroup" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"直播视频-最高画质" key:@"DYYYEnableLiveHighestQuality" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"禁用直播PCDN功能" key:@"DYYYDisableLivePCDN" type:DYYYSettingItemTypeSwitch],

                [DYYYSettingItem itemWithGroupTitle:@"搜索与消息"],
                [DYYYSettingItem itemWithTitle:@"隐藏搜索气泡" key:@"DYYYHideSearchBubble" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏拍照搜同款扫一扫" key:@"DYYYHideScancode" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏大家都在搜" key:@"DYYYHideWords" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏观看历史搜索" key:@"DYYYHideDiscoverFeedEntry" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏通知提示" key:@"DYYYHidePushBanner" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏头像气泡" key:@"DYYYisHiddenAvatarBubble" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏群聊商店" key:@"DYYYHideGroupShop" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏群工具栏" key:@"DYYYHideGroupInputActionBar" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"私信表情保存" key:@"DYYYForceDownloadIMEmotion" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"自动勾选原图" key:@"DYYYisAutoSelectOriginalPhoto" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏朋友关注按钮" key:@"DYYYHideFamiliar" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏添加朋友" key:@"DYYYHideButton" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"隐藏上次看到提示" key:@"DYYYHidePopover" type:DYYYSettingItemTypeSwitch]
            ],

            // ===== 六、数据与维护 =====
            @[
                [DYYYSettingItem itemWithGroupTitle:@"时间属地与数据"],
                [DYYYSettingItem itemWithTitle:@"视频-显示日期时间" key:@"DYYYShowDateTime" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -年-月-日 时:分" key:@"DYYYDateTimeFormat_YMDHM" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -月-日 时:分" key:@"DYYYDateTimeFormat_MDHM" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -时:分:秒" key:@"DYYYDateTimeFormat_HMS" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -时:分" key:@"DYYYDateTimeFormat_HM" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -年-月-日" key:@"DYYYDateTimeFormat_YMD" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"属地前缀" key:@"DYYYLocationPrefix" type:DYYYSettingItemTypeTextField placeholder:@"可以自定义修改 "],
                [DYYYSettingItem itemWithTitle:@"时间属地显示-开关" key:@"DYYYisEnableArea" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -省级" key:@"DYYYisEnableAreaProvince" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -城市" key:@"DYYYisEnableAreaCity" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -市区或县城" key:@"DYYYisEnableAreaDistrict" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -街道或小区" key:@"DYYYisEnableAreaStreet" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"主页-自定义总开关" key:@"DYYYEnableSocialStatsCustom" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -粉丝数量" key:@"DYYYCustomFollowers" type:DYYYSettingItemTypeTextField placeholder:@"填写数字"],
                [DYYYSettingItem itemWithTitle:@"  -获赞数量" key:@"DYYYCustomLikes" type:DYYYSettingItemTypeTextField placeholder:@"填写数字"],
                [DYYYSettingItem itemWithTitle:@"  -关注数量" key:@"DYYYCustomFollowing" type:DYYYSettingItemTypeTextField placeholder:@"填写数字"],
                [DYYYSettingItem itemWithTitle:@"  -互关数量" key:@"DYYYCustomMutual" type:DYYYSettingItemTypeTextField placeholder:@"填写数字"],
                [DYYYSettingItem itemWithTitle:@"视频-自定义总开关" key:@"DYYYEnableVideoStatsCustom" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"  -点赞数量" key:@"DYYYVideoCustomLikes" type:DYYYSettingItemTypeTextField placeholder:@"填写数字"],
                [DYYYSettingItem itemWithTitle:@"  -评论数量" key:@"DYYYVideoCustomComments" type:DYYYSettingItemTypeTextField placeholder:@"填写数字"],
                [DYYYSettingItem itemWithTitle:@"  -收藏数量" key:@"DYYYVideoCustomCollects" type:DYYYSettingItemTypeTextField placeholder:@"填写数字"],
                [DYYYSettingItem itemWithTitle:@"  -分享数量" key:@"DYYYVideoCustomShares" type:DYYYSettingItemTypeTextField placeholder:@"填写数字"],

                [DYYYSettingItem itemWithGroupTitle:@"隐私与系统"],
                [DYYYSettingItem itemWithTitle:@"去除App内更新" key:@"DYYYNoUpdates" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"去青少年弹窗" key:@"DYYYHideteenmode" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"链接解析API" key:@"DYYYInterfaceDownload" type:DYYYSettingItemTypeTextField placeholder:@"不设置，默认"],
                [DYYYSettingItem itemWithTitle:@"无痕模式" key:@"DYYYEnableIncognitoMode" type:DYYYSettingItemTypeSwitch],

                [DYYYSettingItem itemWithGroupTitle:@"维护与热更新"],
                [DYYYSettingItem itemWithTitle:@"清除设置" key:@"DYYYCleanSettings" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"清理缓存" key:@"DYYYCleanCache" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"备份设置" key:@"DYYYBackupSettings" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"恢复设置" key:@"DYYYRestoreSettings" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"一键自检" key:@"DYYYSelfTest" type:DYYYSettingItemTypeButton],
                [DYYYSettingItem itemWithTitle:@"禁用下发配置" key:@"DYYYABTestBlockEnabled" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"启用补丁模式" key:@"DYYYABTestPatchEnabled" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"保存当前配置" key:@"SaveCurrentABTestData" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"本地选择配置" key:@"LoadABTestConfigFile" type:DYYYSettingItemTypeSwitch],
                [DYYYSettingItem itemWithTitle:@"删除本地配置" key:@"DeleteABTestConfigFile" type:DYYYSettingItemTypeSwitch]
            ]
        ];
}

@end
